version: 2

models:
  - name: int_sales
    description: "Intermediate model combining orders and order_items with revenue calculation"
    columns:
      - name: order_id
        description: "Unique identifier for each order"
      - name: product_id
        description: "Product ID from the order"
      - name: quantity
        description: "Quantity ordered"
      - name: list_price
        description: "List price at the time of order"
      - name: discount
        description: "Discount applied to the item"
      - name: revenue
        description: "Revenue calculated after discount"
      - name: order_date
        description: "Date of the order"
      - name: customer_id
        description: "Customer who placed the order"
      - name: store_id
        description: "Store handling the order"

  - name: int_products_enriched
    description: "Intermediate model combining products with brand and category information"
    columns:
      - name: product_id
        description: "Product ID"
      - name: product_name
        description: "Name of the product"
      - name: brand_id
        description: "ID of the brand"
      - name: brand_name
        description: "Name of the brand"
      - name: category_id
        description: "ID of the category"
      - name: category_name
        description: "Name of the category"
      - name: model_year
        description: "Model year of the product"
      - name: list_price
        description: "List price of the product"

  - name: int_store_sales
    description: "Intermediate model combining sales data with store information"
    columns:
      - name: order_date
        description: "Date of the order"
      - name: order_id
        description: "Order ID"
      - name: product_id
        description: "Product ID"
      - name: quantity
        description: "Quantity sold"
      - name: list_price
        description: "Price before discount"
      - name: discount
        description: "Discount applied"
      - name: revenue
        description: "Revenue after discount"
      - name: customer_id
        description: "Customer ID"
      - name: store_id
        description: "Store ID"
      - name: store_name
        description: "Store name"

  - name: int_geo_sales
    description: "Intermediate model combining sales, stores and customer geography"
    columns:
      - name: order_id
        description: "Order ID"
      - name: store_id
        description: "Store ID"
      - name: order_date
        description: "Date of the order"
      - name: product_id
        description: "Product ID"
      - name: quantity
        description: "Quantity ordered"
      - name: list_price
        description: "List price of the product"
      - name: discount
        description: "Discount applied"
      - name: revenue
        description: "Revenue from the order"
      - name: city
        description: "Customer city"
      - name: state
        description: "Customer state"
