version: 2

models:
  - name: int_sales
    description: >
      Modèle intermédiaire regroupant les données de ventes
      enrichies avec les informations de produits, clients, magasins, et employés.
    columns:
      - name: order_id
        description: "Identifiant unique de la commande"
        tests:
          - unique
          - not_null
      - name: order_date
        description: "Date de la commande"
      - name: product_id
        description: "Identifiant du produit"
      - name: customer_id
        description: "Identifiant du client"
      - name: store_id
        description: "Identifiant du magasin"
      - name: staff_id
        description: "Identifiant de l'employé"
      - name: quantity
        description: "Quantité commandée"
      - name: list_price
        description: "Prix unitaire du produit"
      - name: discount
        description: "Réduction appliquée"
      - name: revenue
        description: "Revenu net généré par l'article (prix * quantité * (1 - discount))"

  - name: int_products
    description: >
      Modèle intermédiaire enrichissant les produits avec les informations
      de marque et de catégorie.
    columns:
      - name: product_id
        description: "Identifiant unique du produit"
        tests:
          - unique
          - not_null
      - name: product_name
        description: "Nom du produit"
      - name: brand_id
        description: "Identifiant de la marque"
      - name: brand_name
        description: "Nom de la marque"
      - name: category_id
        description: "Identifiant de la catégorie"
      - name: category_name
        description: "Nom de la catégorie"
      - name: model_year
        description: "Année du modèle"
      - name: list_price
        description: "Prix unitaire de référence"
