version: 2

models:
  - name: stg_brands
    description: "Staging model for the brands table"
    columns:
      - name: brand_id
        description: "Unique identifier for each brand"
      - name: brand_name
        description: "Name of the brand"

  - name: stg_categories
    description: "Staging model for the categories table"
    columns:
      - name: category_id
        description: "Unique identifier for each category"
      - name: category_name
        description: "Name of the category"

  - name: stg_customers
    description: "Staging model for the customers table"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
      - name: first_name
        description: "First name of the customer"
      - name: last_name
        description: "Last name of the customer"
      - name: phone
        description: "Phone number of the customer"
      - name: email
        description: "Email address of the customer"
      - name: street
        description: "Street address of the customer"
      - name: city
        description: "City where the customer lives"
      - name: state
        description: "State where the customer lives"
      - name: zip_code
        description: "ZIP code of the customer's address"

  - name: stg_order_items
    description: "Staging model for the order items table"
    columns:
      - name: order_id
        description: "ID of the order"
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id

      - name: item_id
        description: "ID of the item"
        tests:
          - not_null

      - name: product_id
        description: "ID of the product"
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id

      - name: quantity
        description: "Quantity ordered"

      - name: list_price
        description: "Listed price of the item"

      - name: discount
        description: "Discount applied to the item"

  - name: stg_orders
    description: "Staging model for the orders table"
    columns:
      - name: order_id
        description: "Primary key of the order"
        tests:
          - unique
          - not_null

      - name: customer_id
        description: "Reference to the customer who placed the order"

      - name: order_status
        description: "Status of the order (e.g. placed, shipped, delivered)"

      - name: order_date
        description: "Date when the order was placed"

      - name: required_date
        description: "Expected date of delivery"

      - name: shipped_date
        description: "Date when the order was actually shipped"

      - name: store_id
        description: "ID of the store that handled the order"

      - name: staff_id
        description: "ID of the staff member who processed the order"

  - name: stg_products
    description: "Staging model for the products table"
    columns:
      - name: product_id
        description: "Primary key of the product"
        tests:
          - unique
          - not_null

      - name: product_name
        description: "Name of the product"

      - name: brand_id
        description: "Reference to the brand"

      - name: category_id
        description: "Reference to the product category"

      - name: model_year
        description: "Year the product model was released"

      - name: list_price
        description: "Listed price of the product"

  - name: stg_staffs
    description: "Staging model for staff data"
    columns:
      - name: staff_id
        description: "Primary key for staff"
        tests:
          - unique
          - not_null
      - name: first_name
        description: "First name of the staff"
      - name: last_name
        description: "Last name of the staff"
      - name: email
        description: "Email of the staff"
      - name: phone
        description: "Phone of the staff"
      - name: active
        description: "Staff active status"
      - name: store_id
        description: "Associated store ID"
      - name: manager_id
        description: "Manager's ID"

  - name: stg_stocks
    description: "Staging model for stock data"
    columns:
      - name: store_id
        description: "Store ID where product is stocked"
      - name: product_id
        description: "Product ID"
      - name: quantity
        description: "Quantity of product in stock"

  - name: stg_stores
    description: "Staging model for store data"
    columns:
      - name: store_id
        description: "Store primary key"
        tests:
          - unique
          - not_null
      - name: store_name
        description: "Store name"
      - name: phone
        description: "Store phone number"
      - name: email
        description: "Store email"
      - name: street
        description: "Street address"
      - name: city
        description: "City"
      - name: state
        description: "State"
      - name: zip_code
        description: "ZIP code"
