version: 2

models:
  - name: stg_brands
    description: "Staging model for the brands table"
    columns:
      - name: brand_id
        description: "Unique identifier for each brand"
      - name: brand_name
        description: "Name of the brand"

  - name: stg_categories
    description: "Staging model for the categories table"
    columns:
      - name: category_id
        description: "Unique identifier for each category"
      - name: category_name
        description: "Name of the category"

  - name: stg_customers
    description: "Staging model for the customers table"
    columns:
      - name: customer_id
        description: "Unique identifier for each customer"
      - name: first_name
        description: "First name of the customer"
      - name: last_name
        description: "Last name of the customer"
      - name: phone
        description: "Phone number of the customer"
      - name: email
        description: "Email address of the customer"
      - name: street
        description: "Street address of the customer"
      - name: city
        description: "City where the customer lives"
      - name: state
        description: "State where the customer lives"
      - name: zip_code
        description: "ZIP code of the customer's address"

  - name: stg_order_items
    description: "Staging model for the order items table"
    columns:
      - name: order_id
        description: "ID of the order"
        tests:
          - not_null
          - relationships:
              to: ref('stg_orders')
              field: order_id

      - name: item_id
        description: "ID of the item"
        tests:
          - not_null

      - name: product_id
        description: "ID of the product"
        tests:
          - not_null
          - relationships:
              to: ref('stg_products')
              field: product_id

      - name: quantity
        description: "Quantity ordered"

      - name: list_price
        description: "Listed price of the item"

      - name: discount
        description: "Discount applied to the item"


