version: 2

models:
  - name: sales_summary
    description: "Summary of total revenue, quantity, and orders by store and date"
    columns:
      - name: order_date
        description: "Date of the order"
      - name: store_id
        description: "Store where the order was placed"
      - name: total_revenue
        description: "Total revenue for that store and date"
      - name: total_quantity
        description: "Total quantity sold"
      - name: total_orders
        description: "Number of distinct orders"

  - name: product_performance
    description: "Performance summary per product and store"
    columns:
      - name: product_id
        description: "ID of the product"
      - name: product_name
        description: "Name of the product"
      - name: brand_id
        description: "Brand ID"
      - name: category_id
        description: "Category ID"
      - name: store_id
        description: "Store where the product was sold"
      - name: total_quantity_sold
        description: "Total quantity sold of the product"
      - name: total_revenue
        description: "Total revenue generated by the product"
