version: 2

models:
  - name: sales_summary
    description: "Summary of total revenue, quantity, and orders by store and date"
    columns:
      - name: order_date
        description: "Date of the order"
      - name: store_id
        description: "Store where the order was placed"
      - name: total_revenue
        description: "Total revenue for that store and date"
      - name: total_quantity
        description: "Total quantity sold"
      - name: total_orders
        description: "Number of distinct orders"

  - name: product_performance
    description: "Performance summary per product and store"
    columns:
      - name: product_id
        description: "ID of the product"
      - name: product_name
        description: "Name of the product"
      - name: brand_id
        description: "Brand ID"
      - name: category_id
        description: "Category ID"
      - name: store_id
        description: "Store where the product was sold"
      - name: total_quantity_sold
        description: "Total quantity sold of the product"
      - name: total_revenue
        description: "Total revenue generated by the product"

  - name: geo_sales_summary
    description: "Synthèse des performances de ventes par magasin, incluant localisation, CA, clients, panier moyen, etc."
    columns:
      - name: order_date
        description: "Date of the order"
      - name: store_id
        description: "Identifiant du magasin"
        tests:
          - not_null
      - name: store_name
        description: "Nom du magasin"
      - name: city
        description: "Ville du magasin"
      - name: state
        description: "État du magasin"
      - name: nb_customers
        description: "Nombre de clients distincts ayant passé une commande"
      - name: nb_orders
        description: "Nombre total de commandes"
      - name: total_units_sold
        description: "Nombre total d'articles vendus"
      - name: total_revenue
        description: "Chiffre d'affaires généré par le magasin"
      - name: avg_basket_value
        description: "Valeur moyenne du panier (CA / nombre de commandes)"
